### ISSUE TITLE
Component won't scroll to the top edge of the ScrollView

### ISSUE THREAD

**Issue by platonish** [slorber/react-native-scroll-into-view#1]
Hi, I'm not able to get the required component to scroll into view such that it's top edge touches the top edge of the ScrollView. Right now it only scrolls to the bottom edge of the required component. I'm using the `enabled` prop to decide which component scrolls into view. I tried using `insets: { top: 0 }` but it doesn't work.
Thanks a lot for creating this package btw!

**Comment by slorber** [comment]
Hi
Sorry didn't see the issue notification
If you still have the issue can you provide your code or a snack? Don't really understand your setup

**Comment by jsamr** [comment]
I reproduced this issue today. Same exact situation : enabled + insets top 0.

**Comment by jsamr** [comment]
My section components are wrapped like this:

``` jsx
<ScrollIntoView scrollIntoViewOptions={{ insets: { top: 0 } }}
                onMount={false}
                enabled={this.state.selectedSectionId === section.id}>
  <Section section={section} />
</ScrollIntoView>
```

![scroll-into-bug](https://user-images.githubusercontent.com/3646758/52122123-2c91b180-2622-11e9-9a8f-2248af42aa0a.gif)

**Comment by slorber** [comment]
@jsamr actually I think this is a misunderstand of the purpose of this component.

The point is not to align an element to the top, but to make the element appear in the view. If your element is "under", then the scrollview will scroll so that this element appears, so the element bottom will be aligned with the scrollview bottom, while I think you expect it to align the element top with the scrollview top right?

I'm actually planning to support more features in this project, including the one you seems to want, and also ability to make appear the element at the center of the scrollview.

**Comment by slorber** [comment]
hmmm sorry I think I still misunderstand. 
Can you make your gif slower? It's a bit hard to see if it works as it's very fast.


Can you provide a sample expo project so that I debug your issue?

**Comment by jsamr** [comment]
@slorber OK ; yeah I get your point, two different use cases. I guess the OP had the same intent as me! 
Perhaps you could make that clear or, even better, provide a way to choose between two scroll algorithms?

**Comment by slorber** [comment]
Yeah

I was thinking of providing align = auto | top | bottom | center

will try to work on this when I have time but I'm a bit busy right now

**Comment by slorber** [comment]
hi @jsamr I've just published 1.0 with a new "align" prop which you can set to "top".

Also there are some minor breaking changes (mostly some internal methods not exposed anymore + hoc being renamed + TS migration)

There is also an example of what you seem to achieve:

![](https://camo.githubusercontent.com/388460d90792e67940bd9825ea53df32d2e0186b/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f505054525a52587a4846664f5756706f67762f67697068792e676966)

Can you please tell me if this works fine for you? Don't have much time to test the publication on a real app

**Comment by jsamr** [comment]
@slorber That's really sweet! I am giving it a try this afternoon.

**Comment by jsamr** [comment]
@slorber Metro Haste couldn't bundle the latest release:

> **the package `*/node_modules/react-native-scroll-into-view/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved**

```
Error: While trying to resolve module `react-native-scroll-into-view` from file `*/src/view/molecules/ArticleSummary/Scroller.tsx`, the package `*/node_modules/react-native-scroll-into-view/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`*/node_modules/react-native-scroll-into-view/build/index.js`. Indeed, none of these files exist:
```

**Comment by slorber** [comment]
Hi,

Yes sorry about that, can you try 1.0.3 ?

**Comment by slorber** [comment]
@jsamr is it working fine?

**Comment by jsamr** [comment]
@slorber I'll try this when I finish a feature :slightly_smiling_face:. Give you updates soon.

**Comment by omerman** [comment]
@slorber @jsamr  1.0.3 seem to work with the `align: top` feature, which is exactly what I need! :)
I've tested it in IOS only for now.

Great feature!
If I run into related issues I'll let you know.

**Comment by slorber** [comment]
Great thanks for feedback.I'm closing the issue then. 

Don't hesitate to send me a gif of what you built with it if it's something beautiful

**Comment by jsamr** [comment]
@slorber Thanks a lot, it works great!

**Comment by slorber** [comment]
Great to know :)
