### ISSUE TITLE
Non TS examples

### ISSUE THREAD

**Issue by alz10** [slorber/react-native-scroll-into-view#12]
can you make an examples like the normal code in React? 
Sorry beginner here, I don't understand how this TS works

I need to the Sections example.

**Comment by slorber** [comment]
Hi, can you tell me what exactly you don't understand?

With TS you just have to remove the types 

Regarding the sections example, there are very few types to remove, I think it should be easy to understand, unless you explain why.

https://github.com/slorber/react-native-scroll-into-view/blob/master/example/screens/SectionsScreen.tsx

- `React.createRef<any>()` => `React.createRef()`
- `React.Component<{}>` => `React.Component`
