### ISSUE TITLE
Issue on Orientation

### ISSUE THREAD

**Issue by cvabanuk3** [slorber/react-native-scroll-into-view#19]
react Scroll into view -->  View -->  Open Modal component --> rotate screen 
re renders the App without  Modal

**Comment by slorber** [comment]
Sorry but I don't understand

Le ven. 25 sept. 2020 à 02:44, Siva kumar <notifications@github.com> a
écrit :

**Comment by cvabanuk3** [comment]
Extremely sorry for the inconvenience, confirmed that it was not an issue with this package.
