### ISSUE TITLE
Having the same item scrolled into view after user scrolled manually.

### ISSUE THREAD

**Issue by omerman** [slorber/react-native-scroll-into-view#3]
Hi, first of all thank you for the great lib!

I am having some issues with it,
I have something like this:

```
<Root>
  <CustomScrollView> /* (align top) */
    <ScrollIntoView enabled={isAEnabled}>
      <A>
    </ScrollIntoView>
    ...
  </CustomScrollView>
  <Button onPress={setANotEnabled} />
  <Button onPress={setAEnabled} />
</Root>
```

After scrolling item A into view, aka, setting `isAEnabled` to true, and then user scrolls around manually, and say at some point `isAEnabled` is set to false, and then set to true again..
A is not scrolling into view.

* I will state that if there is a Component B that is scrolled into view and then A is requested to scroll into view afterwards.. it works perfect.

Help?

**Comment by slorber** [comment]
Hi

Will check that next week. 

If you can share a snack with the repro case that would be handy for me

**Comment by slorber** [comment]
closing, feel free to reopen with a repro
