### ISSUE TITLE
Not working in Android 

### ISSUE THREAD

**Issue by darshanksexathought** [slorber/react-native-scroll-into-view#34]
tried implementing the basic scenario in android , the basic example is not working it always stays in the top , I tried with different items when we call `scrollIntoView(viewRef.current)` it will take us to top of the screen instead the the ref that we provided it works perfectly fine in IOS but not in android
parent component
`const CustomScrollView = wrapScrollView(ScrollView);
<CustomScrollView style={styles.scrollView}>
          <SignupScreen />
        </CustomScrollView>`
        
chile component SignupScreen

 ```
 const scrollIntoView = useScrollIntoView();
 const viewRef = useRef(null)

return <>
        <Button title="Scroll a view ref into view" onPress={() => scrollIntoView(viewRef.current)}/>
          
        
  
        <View style={{ height: 100000 }}>
          <Text>Some long ScrollView content</Text>
        </View>
  
        <View ref={viewRef}>
          <Text>Will be scrolled into view on button press</Text>
        </View>
      </>
```

**Comment by slorber** [comment]
I've upgraded the examples recently and tested with Android and it worked. Also integrated this lib with an Android app recently and also worked.

Please test the repo examples, run `yarn start` (it's an expo app) and let me know if this does not work. If it does, it means the problem is more likely in your integration code, and I can't help if you can't provide a full Expo repro.

**Comment by darshanksexathought** [comment]
@slorber do you mind if we can hop on to a meet and see?

**Comment by slorber** [comment]
great, don't hesitate to send a doc PR or whatever if you feel it's useful

**Comment by Stevemoretz** [comment]
Well if you don't use `renderToHardwareTextureAndroid` then it won't work.

**Comment by slorber** [comment]
Did it break on recent RN versions?

Because last time I checked on Android it was working (Expo SDK 41 / RN 0.61). But I only have 1 Android device to test.

**Comment by Stevemoretz** [comment]
> Did it break on recent RN versions?
> 
> Because last time I checked on Android it was working (Expo SDK 41 / RN 0.61). But I only have 1 Android device to test.

Hi thanks for the response I'm using sdk 42 and tried with a bunch of different andorid versions one physical Android 7 and the rest simulators from Android 8 to 10, all failed to move, however if you add one style to the component that you are getting the ref from and add opacity of over 1 eg: style={{opacity:1.1}} it works.

**Comment by MateuszRostkowski** [comment]
Hi 

I'm using it with expo 47 (RN 0.70.5), and adding `renderToHardwareTextureAndroid` resolves issues with android. 

As said in the react-native documentation this prop should be used to small components so I have do it like so:

```tsx
<>
  <View renderToHardwareTextureAndroid ref={viewRef} />
  <Component />
</>
```

On iOS it works out of the box.
