### ISSUE TITLE
Question: How to use `scrollIntoView`outside of `CustomScrollView`?

### ISSUE THREAD

**Issue by mrzmyr** [slorber/react-native-scroll-into-view#44]
Hi @slorber, I want to implement a back to top button. How do I use `scrollIntoView` outside `CustomScrollView`? The button for the back button should be sticky, that's why I want to have it outside the scroll container. 

Thank you :)

**Comment by slorber** [comment]
it is 100% impossible sorry, because this method actually controls the scroll position of the parent scrollview, so a scrollview is mandatory
