### ISSUE TITLE
Sections array with strings doesn't work

### ISSUE THREAD

**Issue by Rajdeepc** [slorber/react-native-scroll-into-view#7]
@slorber  
I am trying to create three buttons with Text like 
`const Sections = ['OVERVIEW','MODELS','GALLERY']`

The below code doesnt work:
```
const Sections = ['OVERVIEW','MODELS','GALLERY']
    const sectionsRefs = (link: http://Sections.map) Sections.map(
        _section => React.createRef<any>()
    );

    const scrollSectionIntoView = (section: any) => {
      sectionsRefs[section].current!.scrollIntoView({ align: 'top' });
    };
```
  
But the below code works:
```
 const Sections = ['0','1','2'];

    const sectionsRefs = (link: http://Sections.map) Sections.map(
        _section => React.createRef<any>()
    );

    const scrollSectionIntoView = (section: any) => {
      sectionsRefs[section].current!.scrollIntoView({ align: 'top' });
    };
```

**Comment by slorber** [comment]
Answererd by twitter, not really related to this lib anyway.

      sectionsRefs[section].current!.scrollIntoView({ align: 'top' });

=> sectionsRefs is an array, and section is a string. You should get the ref by using the section index, not the section name/string
