### ISSUE TITLE
ScrollIntoView doesn't work when i use this components inside the ScrollView

### ISSUE THREAD

**Issue by Rajdeepc** [slorber/react-native-scroll-into-view#8]
I have a parent component which is wrapped with a <ScrollView/> so when i try to use this component as a child component this doesn't work whereas this works when i use this component as a parent component.

My current requirement is to use this component as a child component whereas the parent is wrapped is a ScrollView. 

Any work around? @slorber

**Comment by slorber** [comment]
Can you share a repro so I can take a look? I don't have much time to do
support so please help me win time

Le dim. 18 août 2019 à 17:17, Rajdeep Chandra <notifications@github.com> a
écrit :
